version: 1
update_configs:
# jdk-8 images
  - package_manager: "docker"
    directory: "/8/alpine"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/8/debian"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/8/nanoserver-1809"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/8/windowsservercore-1809"
    update_schedule: "weekly"
# jdk-11 images
  - package_manager: "docker"
    directory: "/11/debian"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/11/nanoserver-1809"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/11/windowsservercore-1809"
    update_schedule: "weekly"
